classes=TicTacToeGame.class TicTacToe.class Cell.class

all: $(classes)

TicTacToeGame.class : TicTacToeGame.java
	javac TicTacToeGame.java

TicTacToe.class : TicTacToe.java
	javac TicTacToe.java
	
Cell.class : Cell.java
	javac Cell.java

clean:
	rm $(classes)
